export const IconIdentifier = {
  Home: 'home',
  Info: 'info',
  Groups: 'groups',
  Calendar: 'calendar',
  Soccer: 'soccer',
  Profile: 'profile',
  Logout: 'logout',
  Star: 'star',
  Error: 'error',
  Call: 'call',
  Check: 'check-icon',
  Facebook: 'facebook',
  Google: 'google',
  LinkedIn: 'linkedin',
  Mail: 'mail',
  EyeHide: 'eye-hide',
  Eye: 'eye',
  Bell: 'bell',
  ChevronLeft: 'chevron-left',
  ChevronRight: 'chevron-right',
};
